# This file establishes the necessary resources on Azure to create a Demo Webserver using Ubuntu
# Authentication from file $HOME/.azure/credentials

- name: 01 - Create Resource Group and VNET
  hosts: localhost
  connection: local
  vars:
    local_ip: "nada-none"
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
  vars_files:
    - ./config.yml

  tasks:
  
    - name: STARTING NOW ...
      debug: msg="Starting now @ {{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"
      
    - name: Getting your Public IP Address
      local_action:
        module: uri
        url: http://checkip.amazonaws.com
        return_content: yes
      register: local_ip
      failed_when: not local_ip.content | regex_search ('(\d+).(\d+).(\d+).(\d+)\n')

    # Allow access from /24 instead of /32 host
    - name: Set Public Network Variable
      set_fact:
        ALLOWED_SRC_ADDRESS: "{{ local_ip.content | ipsubnet (24,0) }}"
        #ALLOWED_SRC_ADDRESS: "{{ local_ip.content | ipaddr ('host') }}"

    - name: Your Public IP Net for allowed Inbound traffic
      debug: var=ALLOWED_SRC_ADDRESS
      
    - name: Create Resource Group {{ RESOURCE_GROUP }}
      azure_rm_resourcegroup:
        name: "{{ RESOURCE_GROUP }}"
        location: "{{ DEFAULT_LOCATION }}"

    - name: Create Virtual Network {{ VNET1 }} (10.1.0.0/16)
      azure_rm_virtualnetwork:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ VNET1 }}"
        address_prefixes: "10.1.0.0/16"

    - name: Add Subnet {{ VNET_SUBNET_MGMT }} (10.1.1.0/24) to VNET {{ VNET1 }}
      azure_rm_subnet:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ VNET_SUBNET_MGMT }}"
        address_prefix: "10.1.1.0/24"
        virtual_network: "{{ VNET1 }}"

    - name: Add Subnet {{ VNET_SUBNET_EXT }} (10.1.10.0/24) to VNET {{ VNET1 }}
      azure_rm_subnet:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ VNET_SUBNET_EXT }}"
        address_prefix: "10.1.10.0/24"
        virtual_network: "{{ VNET1 }}"

    - name: Add Subnet {{ VNET_SUBNET_INT }} (10.1.20.0/24) to VNET {{ VNET1 }}
      azure_rm_subnet:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ VNET_SUBNET_INT }}"
        address_prefix: "10.1.20.0/24"
        virtual_network: "{{ VNET1 }}"

    - name: Create Storage Account sa{{ STUDENT_ID }}{{ date }} in Resource Group {{ RESOURCE_GROUP }}
      azure_rm_storageaccount:
        location: "{{ DEFAULT_LOCATION }}"
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "sa{{ STUDENT_ID }}{{ date }}"
        account_type: Standard_LRS

    - name: Edit {{ NODE_NAME }}-{{ STUDENT_ID }}-sg0 Security Group in Resource Group {{ RESOURCE_GROUP }} (Allow DATA and Access)
      azure_rm_securitygroup:
          resource_group: "{{ RESOURCE_GROUP }}"
          name: "{{ NODE_NAME }}-{{ STUDENT_ID }}-sg0"
          purge_rules: yes
          rules:
              - name: 'Allow_SSH'
                protocol: Tcp
                source_address_prefix: '{{ ALLOWED_SRC_ADDRESS }}'
                destination_port_range: 22
                access: Allow
                priority: 100
                direction: Inbound
              - name: 'Allow_HTTP_80'
                protocol: Tcp
                source_address_prefix: '{{ ALLOWED_SRC_ADDRESS }}'
                destination_port_range: 80
                access: Allow
                priority: 101
                direction: Inbound
              - name: 'Allow_HTTPS_443'
                protocol: Tcp
                source_address_prefix: '{{ ALLOWED_SRC_ADDRESS }}'
                destination_port_range: 443
                access: Allow
                priority: 102
                direction: Inbound
              - name: 'Allow_TCP_2181_kafka'
                protocol: Tcp
                source_address_prefix: '{{ ALLOWED_SRC_ADDRESS }}'
                destination_port_range: 2181
                access: Allow
                priority: 103
                direction: Inbound  
              - name: 'Allow_TCP_9092_kafka'
                protocol: Tcp
                source_address_prefix: '{{ ALLOWED_SRC_ADDRESS }}'
                destination_port_range: 9092
                access: Allow
                priority: 104
                direction: Inbound                     
              - name: 'Allow_TCP_8080_to_8089'
                protocol: Tcp
                source_address_prefix: '{{ ALLOWED_SRC_ADDRESS }}'
                destination_port_range: 8080-8089
                access: Allow
                priority: 105
                direction: Inbound
              - name: 'Allow_TCP_8443'
                protocol: Tcp
                source_address_prefix: '{{ ALLOWED_SRC_ADDRESS }}'
                destination_port_range: 8443
                access: Allow
                priority: 106
                direction: Inbound

    - debug: msg="Finishing ... @ {{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"
