# Deploy a Resource Group, VNET, Subnets, NSG
# Authentication from file $HOME/.azure/credentials

- name: 01 - Create Resource Group and VNET
  hosts: localhost
  connection: local
  vars:
    local_ip: "nada-none"
    date: "{{ lookup('pipe', 'date +%Y%m') }}"
  vars_files:
    - ./config.yml

  tasks:

    - name: STARTING NOW ...
      debug: msg="Starting now @ {{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"

    - name: Getting your Public IP Address
      local_action:
        module: uri
        url: http://checkip.amazonaws.com
        return_content: yes
      register: local_ip
      failed_when: not local_ip.content | regex_search ('(\d+).(\d+).(\d+).(\d+)\n')

    # Allow access from /24 net or /32 host
    - name: Set Public Network Variable
      set_fact:
        #ALLOWED_SRC_ADDRESS: "{{ local_ip.content | ipsubnet (24,0) }}"
        ALLOWED_SRC_ADDRESS: "{{ local_ip.content | ipaddr ('host') }}"

    - name: Your Public IP Net for allowed Inbound traffic
      debug: var=ALLOWED_SRC_ADDRESS

    - name: Create Resource Group {{ RESOURCE_GROUP }}
      azure_rm_resourcegroup:
        name: "{{ RESOURCE_GROUP }}"
        location: "{{ DEFAULT_LOCATION }}"

    - name: Create Virtual Network {{ VNET1 }} ({{ VNET_CIDR }})
      azure_rm_virtualnetwork:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ VNET1 }}"
        address_prefixes: "{{ VNET_CIDR }}"

    - name: Add Subnet {{ SUBNET_MGMT }} {{ MGMT_PREFIX }} to VNET {{ VNET1 }}
      azure_rm_subnet:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ SUBNET_MGMT }}"
        address_prefix: "{{ MGMT_PREFIX }}"
        virtual_network: "{{ VNET1 }}"

    - name: Add Subnet {{ SUBNET_EXT }} ({{ EXT_PREFIX }}) to VNET {{ VNET1 }}
      azure_rm_subnet:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ SUBNET_EXT }}"
        address_prefix: "{{ EXT_PREFIX }}"
        virtual_network: "{{ VNET1 }}"

    - name: Add Subnet {{ SUBNET_INT }} ({{ INT_PREFIX }}) to VNET {{ VNET1 }}
      azure_rm_subnet:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ SUBNET_INT }}"
        address_prefix: "{{ INT_PREFIX }}"
        virtual_network: "{{ VNET1 }}"

    - name: Create vlab-{{ STUDENT_ID }}-sg0 Security Group
      azure_rm_securitygroup:
          resource_group: "{{ RESOURCE_GROUP }}"
          name: "vlab-{{ STUDENT_ID }}-sg0"
          purge_rules: no
          rules:
              - name: 'Allow_TCP_{{item}}'
                protocol: Tcp
                source_address_prefix: '{{ ALLOWED_SRC_ADDRESS }}'
                destination_port_range: "{{item}}"
                access: Allow
                priority: "{{ my_idx|int + 100 }}"
                direction: Inbound
      loop: "{{ALLOWED_PORTS}}"
      loop_control:
        index_var: my_idx

    - debug: msg="Finishing ... @ {{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"
