# Update/Install AS3, TS & DO RPMs

- name: 04 Install AS3, TS & DO RPMs
  hosts: localhost
  connection: local
  vars:
    bigipmgmtip: ""
    bigipmgmtinfo: ""
    provider:
      server: "{{ bigipmgmtip }}"
      server_port: "443"
      user: "{{ADMINUSERNAME}}"
      password: "{{ADMINPASSWORD}}"
      validate_certs: no
      transport: "rest"

  vars_files:
    - ./config.yml

  tasks:
    - name: Getting BIG-IP Mgmt Info
      azure_rm_publicipaddress_info:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ BIGIP_NAME }}-{{ STUDENT_ID }}-mgmt-pip"
      register: bigipmgmtinfo

    - name: Getting BIG-IP Mgmt Info
      set_fact:
        bigipmgmtip: "{{bigipmgmtinfo.publicipaddresses[0].ip_address }}"

    - name: Setting BIG-IP variables
      bigip_command:
        provider: "{{ provider }}"
        commands:
          - modify sys db ui.advisory.enabled value true
          - modify sys db ui.advisory.color value "blue"
          - modify sys db ui.advisory.text value "BIG-IP Azure - {{STUDENT_ID}}"
          - modify sys db ui.system.preferences.recordsperscreen value 100
          - modify sys httpd auth-pam-idle-timeout 7200
        warn: false

    - name: Download and Install Application Services 3 (AS3) RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.23.0/f5-appsvcs-3.23.0-5.noarch.rpm"
        f5app_services_package_path: "/tmp/f5-appsvcs-3.23.0-5.noarch.rpm"

    - name: Download and Install Telemetry Streaming (TS) RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.15.0/f5-telemetry-1.15.0-4.noarch.rpm"
        f5app_services_package_path: "/tmp/f5-telemetry-1.15.0-4.noarch.rpm"

    - name: Download and Install Declarative Onboarding (DO) RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.16.0/f5-declarative-onboarding-1.16.0-8.noarch.rpm"
        f5app_services_package_path: "/tmp/f5-declarative-onboarding-1.16.0-8.noarch.rpm"
