- name: Deploy an App using AS3
  hosts: localhost
  connection: local
  vars:
    bigipmgmtip: ""
    bigipmgmtinfo: ""
    bigipvsip: ""
    provider:
      user: "{{ ADMINUSERNAME }}"
      password: "{{ ADMINPASSWORD }}"
      server: "{{ bigipmgmtip }}"
      validate_certs: no
      server_port: 443
      timeout: 60
  vars_files:
    - ./config.yml

  tasks:

    - name: Getting BIG-IP Mgmt Info
      azure_rm_publicipaddress_info:
        resource_group: "{{ RESOURCE_GROUP }}"
        name: "{{ BIGIP_NAME }}-{{ STUDENT_ID }}-mgmt-pip"
      register: bigipmgmtinfo

    - name: Setting variables
      set_fact:
        bigipmgmtip: "{{bigipmgmtinfo.publicipaddresses[0].ip_address }}"

    - name: MGMT IP
      debug: msg="{{bigipmgmtip}}"

    - name: Deploying AS3 configuration
      bigip_appsvcs_extension:
        content: "{{ lookup('file', '{{ playbook_dir }}/as3.json') }}"
        #content: "{{ lookup('file', '{{ playbook_dir }}/as3-empty.json') }}"
        state: present
        provider: "{{ provider }}"
